### ISSUE TITLE
weechat theme

### ISSUE THREAD

**Issue by microo8** [Barbarossa93/Muspelheim#1]
Hi how can I configure weechat to look like yours?
I tried just copying the [took] and [colors] to weechat.conf but nothing.
Just some colors have changed

**Comment by Barbaross93** [comment]
I'm going to be honest, weechat configs are notoriously difficult to share. I don't know exactly what you need to do to replicate my setup :( I can say that at the very least you'll need this [script](https://weechat.org/scripts/source/text_item.py.html/) in order to get the 'snake' line. If I had to guess, you'll also want to copy over the `[bar]` section in `weechat.conf`, as that creates the snake line.

**Comment by microo8** [comment]
weechat configs are hard. I've copied all of your `.config/weechat` but
there is no snake. And the channels on top don't look like yours :/

**Comment by Barbaross93** [comment]
Are you sure the script I mentioned is installed and loaded? Unfortunately I'm unsure about top bar channels, I would think copying everything shoudl do the trick :(

**Comment by microo8** [comment]
Yes, the script is loaded, but just a line is visible. No snake thing on
top and bottom. Is it because I use a wrong font (Ubuntu Mono)?

**Comment by Barbaross93** [comment]
OH! Its because the important bit is in `plugins.conf` but I didn't upload it because it has sensitive info. Try adding this to your plugins.conf:
```
python.text_item.bottom_text = "all ${color:red}┏━━━━━━━━━━━━━┛"
python.text_item.input_char = "all ${color:red}┗━${color:reset}"
python.text_item.input_text = "all ${color:red}┗━${color:reset}"
python.text_item.interval = "0"
python.text_item.top = "┗━━━━━━━━━━━━━━━┓"
python.text_item.top_char = "all ${color:red}┏━ ${color:darkgray}■"
python.text_item.top_text = "all ${color:red}┗━━━━━━━━━━━━━┓"
```

**Comment by microo8** [comment]
Wow thanks, thats great! It works! Beautifull 8-O

**Comment by Barbaross93** [comment]
Awesome! Sorry it took so long to figure out

**Comment by microo8** [comment]
One more thing. When I want the 'snake' to be yellow, I can change the
plugins.conf:

> python.text_item.bottom_text = "all ${color:yellow}┏━━━━━━━━━━━━━┛"
> python.text_item.input_char = "all ${color:yellow}┗━${color:reset}"
> python.text_item.input_text = "all ${color:yellow}┗━${color:reset}"
> python.text_item.interval = "0"
> python.text_item.top = "┗━━━━━━━━━━━━━━━┓"
> python.text_item.top_char = "all ${color:yellow}┏━ ${color:darkgray}■"
> python.text_item.top_text = "all ${color:yellow}┗━━━━━━━━━━━━━┓"

And the top and bottom changes, but where I can change the vertical
line?

sorry for being annoying

**Comment by microo8** [comment]
ok I have it, it's in `weechat.conf`: `[color] chat_prefix_suffix = yellow`
