### ISSUE TITLE
issue with yambar config

### ISSUE THREAD

**Issue by maroozm** [Barbarossa93/Muspelheim#2]
Hey, really sorry to ask like this by why do I get this error while using your yambar config?
bar.left.script.content.list.items.map: invalid key: tag

**Comment by Barbaross93** [comment]
Do you have the correct path in your `config.yml` for the script? Are you running herbstluftwm?

**Comment by maroozm** [comment]
Yes, I am running herbstluftwm and I have correct paths. When i run the hlwm.sh, it works perfectlly with this output
tag_1|string|u
tag_2|string|o
tag_3|string|f
tag_4|string|e
tag_5|string|e
tag_6|string|e
tag_7|string|e
tag_8|string|e
tag_9|string|e
tag_0|string|e

**Comment by Barbaross93** [comment]
Oh, are you running the latest yambar-git?

**Comment by maroozm** [comment]
yambar version is 1.8.0 and i installed it from xbps-src on void. i think its the latest version.

**Comment by Barbaross93** [comment]
That's the current release. Install yambar straight from the git repository. It contains unreleased changes that my config relies on.

**Comment by Barbaross93** [comment]
Closing this as I'm assuming you figured it out. Otherwise, feel free to re-open.
